FROM ubuntu:16.04
MAINTAINER Jaehyeon Kim "dottami@gmail.com"
ENV REFRESHED_AT 2014-06-01

# enabling ip related commands
# https://github.com/wso2/dockerfiles/issues/41
RUN apt-get -yqq update && apt-get -yqq install iproute2

